version: '3'
services:
  redoc:
    image: redocly/redoc
    ports:
      - 8080:80
    environment:
      - SPEC_URL=./openapi.yaml
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
