openapi: 3.1.0
info:
  title: Car Booking
  version: 0.0.1
  description: This is a reservation server for shared vehicles.
  contact:  
    name: diverwil1995
    url: https://github.com/diverwil1995/car-booking
    email: diverwil1995@gmail.com
  license: 
    name: All rights reserved
    url: "#"
servers: 
  - url: http://localhost:1323

paths:
  "/users":
    post:
      summary: Register a new user.
      operationId: createUser
      security:
        - jwt_auth: []
      description: > 
        This operation allows creating a new user in system.
        It requires the user's name and password as input.
        If the operation is successful, it will return the user structure, including the UUID.
      
components: 
  securitySchemes: 
    jwt_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
